"""Initial migration

Revision ID: 37c3fcc537b0
Revises: 
Create Date: 2025-11-13 13:37:21.366449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37c3fcc537b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vc_id', sa.String(), nullable=False),
    sa.Column('holder_did', sa.String(), nullable=False),
    sa.Column('issuer_did', sa.String(), nullable=False),
    sa.Column('type', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('proof', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('onchain_tx_hash', sa.String(), nullable=True),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('storage_cid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_holder_did_status', 'credentials', ['holder_did', 'status'], unique=False)
    op.create_index(op.f('ix_credentials_hash'), 'credentials', ['hash'], unique=False)
    op.create_index(op.f('ix_credentials_holder_did'), 'credentials', ['holder_did'], unique=False)
    op.create_index(op.f('ix_credentials_issuer_did'), 'credentials', ['issuer_did'], unique=False)
    op.create_index(op.f('ix_credentials_vc_id'), 'credentials', ['vc_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('HOLDER', 'ISSUER', 'VERIFIER', name='userrole'), nullable=False),
    sa.Column('did', sa.String(), nullable=True),
    sa.Column('wallet_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_did'), 'users', ['did'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_wallet_address'), 'users', ['wallet_address'], unique=False)
    op.create_table('dids',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('did', sa.String(), nullable=False),
    sa.Column('controller', sa.String(), nullable=True),
    sa.Column('document', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dids_did'), 'dids', ['did'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dids_did'), table_name='dids')
    op.drop_table('dids')
    op.drop_index(op.f('ix_users_wallet_address'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_did'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_credentials_vc_id'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_issuer_did'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_holder_did'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_hash'), table_name='credentials')
    op.drop_index('idx_holder_did_status', table_name='credentials')
    op.drop_table('credentials')
    # ### end Alembic commands ###

